linters:
  # We want to gradually introduce new linters to the project
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - decorder
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - ginkgolinter
    - gocheckcompilerdirectives
    - goimports
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - promlinter
    - staticcheck
    - stylecheck
    - typecheck
    - tagalign
    - unconvert
    - unused
    - whitespace

    # - dupl
    # - cyclop
    # - funlen

linters-settings:
  stylecheck:
    checks: ["*", "-ST1003"]
  exhaustive:
    check:
      - switch
      - map
    ignore-enum-types: "ResourceName|FileMode|ProgrammingLanguage"
    # - cyclop
    # - funlen
issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
